### ISSUE TITLE
Error when executing training scripts

### ISSUE THREAD

**Issue by MinionAttack** [e-bug/syncap#3]
Hi, I'm trying to run the training scripts but I'm getting an error that I don't understand.

If I try to run the `train.sh` script from `experiments/coco_heldout_1/butr_weight` I get:

```
usage: train.py [-h] [--seed SEED] [--print-freq PRINT_FREQ]
                [--workers WORKERS] [--cpu] [--batch-size BATCH_SIZE]
                [--max-epochs MAX_EPOCHS]
                [--epochs-early-stopping EPOCHS_EARLY_STOPPING]
                [--max-caption-len MAX_CAPTION_LEN] [--criterion CRITERION]
                [--regularization REGULARIZATION]
                [--generation-criterion GENERATION_CRITERION]
                [--ranking-criterion RANKING_CRITERION]
                [--gradnorm-criterion GRADNORM_CRITERION]
                [--mask-prob MASK_PROB] [--mask-type {tags,words,both}]
                [--image-features-filename IMAGE_FEATURES_FILENAME]
                [--dataset-splits-dir DATASET_SPLITS_DIR]
                [--embeddings EMBEDDINGS]
                [--objective {GENERATION,JOINT,MULTI}]
                [--teacher-forcing TEACHER_FORCING] [--dropout DROPOUT]
                [--encoder-learning-rate ENCODER_LEARNING_RATE]
                [--decoder-learning-rate DECODER_LEARNING_RATE]
                [--grad-clip GRAD_CLIP] [--gradnorm-alpha GRADNORM_ALPHA]
                [--gradnorm-learning-rate GRADNORM_LEARNING_RATE]
                [--checkpoints-dir CHECKPOINTS_DIR]
                [--logging-dir LOGGING_DIR]
                [--embeddings-path EMBEDDINGS_PATH]
                [--image-normalize {imagenet,scaleimagenet}]
                [--fine-tune-encoder] [--dont-fine-tune-word-embeddings]
                [--dont-fine-tune-caption-embeddings]
                [--dont-fine-tune-image-embeddings]
                {sat,butd,butr,butr_mean,butr_weight} ...
train.py: error: argument model: invalid choice: 'butr_attn' (choose from 'sat', 'butd', 'butr', 'butr_mean', 'butr_weight')
```
So in line 30 of `train.sh` I changed `butr_attn` to `butr_weight` but then I get:

```
Traceback (most recent call last):
  File "/home/iago/Escritorio/SynCap/code/train.py", line 470, in <module>
    main(args)
  File "/home/iago/Escritorio/SynCap/code/train.py", line 415, in main
    gen_criterion, rank_criterion)
  File "/home/iago/Escritorio/SynCap/code/train.py", line 86, in calc_initial_losses
    scores, decode_lengths, extras = model(images, target_captions, decode_lengths, teacher_forcing)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Gather got an input of invalid size: got [50, 19, 10004], but expected [50, 15, 10004] (gather at /opt/conda/conda-bld/pytorch_1570910687230/work/torch/csrc/cuda/comm.cpp:226)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f4a09d5f687 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x2ad (0x7f4a0fc1ce8d in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x78ee82 (0x7f4a3e07be82 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x206aa6 (0x7f4a3daf3aa6 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #14: THPFunction_apply(_object*, _object*) + 0x9ff (0x7f4a3dd8bacf in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
```
The problem is here:

`RuntimeError: Gather got an input of invalid size: got [50, 19, 10004], but expected [50, 15, 10004] (gather at /opt/conda/conda-bld/pytorch_1570910687230/work/torch/csrc/cuda/comm.cpp:226)`

There is a difference of 4 in the second value.

I thought it might be a specific problem with this training so I tried the `train.sh` script from `experiments/coco_heldout_1_ccg_inter/butd` as well and I get the same error:

```
Traceback (most recent call last):
  File "/home/iago/Escritorio/SynCap/code/train.py", line 470, in <module>
    main(args)
  File "/home/iago/Escritorio/SynCap/code/train.py", line 432, in main
    args.mask_prob, args.mask_type)
  File "/home/iago/Escritorio/SynCap/code/train.py", line 133, in train
    teacher_forcing, mask_prob, mask_type)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Gather got an input of invalid size: got [25, 33, 10320], but expected [25, 29, 10320] (gather at /opt/conda/conda-bld/pytorch_1570910687230/work/torch/csrc/cuda/comm.cpp:226)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f38c27e9687 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x2ad (0x7f38c86a6e8d in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x78ee82 (0x7f38f6b05e82 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x206aa6 (0x7f38f657daa6 in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #14: THPFunction_apply(_object*, _object*) + 0x9ff (0x7f38f6815acf in /home/iago/anaconda3/envs/syncap/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
```

With:

`RuntimeError: Gather got an input of invalid size: got [25, 33, 10320], but expected [25, 29, 10320] (gather at /opt/conda/conda-bld/pytorch_1570910687230/work/torch/csrc/cuda/comm.cpp:226)`

There is a difference of 4 in the second value too.

What is the difference that causes the error to occur?

Yours faithfully.

**Comment by MinionAttack** [comment]
I found a quick solution to the problem. Not wanting to touch the code, I looked at the paper and saw that it says:

> All models are trained on an NVIDIA TitanX GPU in a shared cluster.

My computer has 2 GPUs so I googled the error and found out that the mismatch is caused by splitting the data with DataParallel.

[Section: My recurrent network doesn’t work with data parallelism](https://pytorch.org/docs/stable/notes/faq.html)
[[Error] RuntimeError: Gather got an input of invalid size [problem] DataParallel](https://www.programmersought.com/article/68642184736/)

So, for an easy and quick solution I've changed in `train.py`:

```
# Move to GPU, if available
if torch.cuda.device_count() > 1:
    model = nn.DataParallel(model)
model = model.to(device)
```

to

```
# Move to GPU, if available
# if torch.cuda.device_count() > 1:
    # model = nn.DataParallel(model)
model = model.to(device)
```
And now it works using only 1 GPU.

Yours faithfully.
